
// long-form coaching cues + demo search terms, keyed to the pose table above
const EXTRA={
"Deep squats":["<strong>Form:</strong> Feet shoulder-width, heels down. Hips go back first, then straight down until you are nearly sitting on your heels — torso and shins stay parallel to each other, ankles folding to about 65° at the bottom","deep+bodyweight+squat+mobility+drill"],
"Parallel squats":["<strong>Form:</strong> Same pattern, but stop when the thighs reach parallel. Chest stays prouder than the deep squat; knees track over the second toe and the heels never lift","parallel+squat+form+bodyweight"],
"Knee circles":["<strong>Form:</strong> Knees bent, hands resting on them, feet planted. Circle the knees one direction, reverse at the halfway chime. <strong>Ankle note:</strong> weight even on both feet — shrink the circle if the right ankle complains.","standing+knee+circles+joint+mobility"],
"Reverse lunges":["<strong>Form:</strong> Step back about two feet, landing on the ball of the back foot. Front shin stays vertical — knee stacked over ankle — both knees near 90°, back knee hovering an inch or two off the floor","reverse+lunge+proper+form"],
"Hip hinges":["<strong>Form:</strong> Soft knees, push the hips straight BACK — not down. Chest travels forward, spine stays long, arms hang on the bar path. <strong>Training link:</strong> this is your narrow sumo deadlift pattern, grooved daily without load.","hip+hinge+drill+deadlift+pattern"],
"Folded cat-cows":["<strong>Form:</strong> Knees bent, hands resting on them. Round the spine on the exhale, arch and open the chest on the inhale. <strong>Training link:</strong> targets T4–T8 extension — where your chronic mid-back pain lives.","standing+folded+cat+cow+spinal+mobility"],
"Cobra press-ups":["<strong>Form:</strong> Face down, hands under shoulders. Press the chest up, hips stay on the floor. Lower with control. <strong>Shoulder note:</strong> elbows tucked close to the ribs — flaring them loads the right AC joint.","cobra+press+up+mckenzie+extension"],
"Pedaling down dog":["<strong>Form:</strong> Alternate pressing one heel toward the floor while the other knee bends. Slow and rhythmic. <strong>Ankle note:</strong> gentle calf and Achilles work with no peroneal load — keep the foot tracking straight, not rolling outward.","pedaling+downward+dog+calf+stretch"],
"Tuck + untuck":["<strong>Form:</strong> Lie flat, knees bent, feet flat. Only the pelvis moves: flatten the low back into the floor, then let it arch gently away. Everything above the ribs stays quiet on the ground","pelvic+tilt+tuck+untuck+core+control"],
"90/90 with a fold":["<strong>Form:</strong> Z-sit: front leg's outer thigh and shin flat on the floor, back leg's inner thigh down with the shin pointing straight behind you. Sit tall, then hinge forward over the front shin without rounding","90+90+hip+stretch+with+forward+fold"],
"Thread the needle":["<strong>Form:</strong> On hands and knees. Reach one arm to the ceiling, then slide it under the opposite armpit and let the shoulder rest toward the floor. Switch at the halfway chime. <strong>Training link:</strong> thoracic rotation plus scapular mobility — your mid-back and right shoulder IR limitation.","thread+the+needle+thoracic+rotation+stretch"],
"Plank hold":["<strong>Form:</strong> Forearms down, body in one straight line. Squeeze the glutes, brace, don't let the hips sag or pike. <strong>Shoulder note:</strong> forearm plank is kinder to the right AC joint — push the floor away to fire the serratus, same cue as your landmine press.","forearm+plank+proper+form+serratus"]};
MOVES.forEach(m=>{m.long=EXTRA[m.n][0]; m.q=EXTRA[m.n][1];});
