const EXTRA={
"Breath and pelvic floor release":["<strong>Form:</strong> Sit tall on a chair. One hand on the belly, one on the chest. Inhale into the belly hand and feel the pelvic floor soften and widen; exhale and simply let it be","pelvic+floor+relaxation+breathing+birth+preparation"],
"Hands-and-knees pelvic rocking":["<strong>Form:</strong> Wrists under shoulders, rock the pelvis slowly forward and back, spine near neutral. <strong>Why:</strong> encourages an optimal anterior fetal position and mobilises the sacroiliac joints. Also one of the most-used labour positions, so the pattern is worth knowing in your body.","hands+and+knees+pelvic+tilt+rocking+pregnancy"],
"Birth ball hip circles":["<strong>Form:</strong> Sit tall on the ball, feet flat and wide so feet and ball form a tripod, hips level with or above the knees. Circle from the pelvis like a slow hula hoop — the shoulders stay quiet. Reverse direction at the halfway chime","birth+ball+hip+circles+pregnancy"],
"Supported deep squat":["<strong>Form:</strong> Hold a counter or chair back. Lower only as far as is comfortable, heels down if possible, knees tracking out. Rise slowly on the exhale. <strong>Why:</strong> squatting can widen the pelvic outlet substantially. <strong>Caution:</strong> depth is earned — go only as deep as feels steady today, and come up slowly.","supported+deep+squat+pregnancy+birth+preparation"],
"Side-lying clamshells":["<strong>Form:</strong> Hips stacked, knees bent, heels glued together. Only the top knee opens — the pelvis must not roll backward. The lift is small; the control is the exercise","side+lying+clamshell+pregnancy+glute+medius"],
"Supported butterfly with rock":["<strong>Form:</strong> Sit elevated on a cushion, soles together, knees open, rock gently side to side. Never push the knees down. <strong>Why:</strong> adductor flexibility determines how wide the pelvis can open. Forcing range can destabilise an already-softened pelvis.","bound+angle+pose+pregnancy+hip+opening"],
"Kneeling lunge with support":["<strong>Form:</strong> Half-kneeling, cushion under the back knee, hand on a chair, shift weight gently forward. Switch at the halfway chime. <strong>Why:</strong> asymmetric hip positions help the baby navigate the pelvis and are commonly used to resolve a stalled labour.","half+kneeling+lunge+pregnancy+hip+flexor"],
"Standing wall pelvic tilts":["<strong>Form:</strong> Back against a wall, feet a step forward. Flatten the low back into the wall on the exhale, release on the inhale. Small and controlled. <strong>Why:</strong> conscious pelvic control reduces back pain now and gives you an active tool for back labour.","standing+wall+pelvic+tilt+pregnancy"],
"Pelvic floor coordination":["<strong>Form:</strong> Both hands rest low on the belly. On the exhale, a gentle pelvic floor lift; on the inhale, a complete, deliberate release. The release is the important half for birth","pelvic+floor+contract+and+release+pregnancy"],
"Wide-knee child's pose":["<strong>Form:</strong> Knees wide, big toes together, sitting back toward the heels, belly resting between the knees. <strong>Why:</strong> passive pelvic floor lengthening, and a genuine rest position for the low back.","wide+knee+childs+pose+pregnancy"],
"Left side-lying rest":["<strong>Form:</strong> Left side, pillow between the knees and under the belly. Return to the soft downward-widening breath from movement one. <strong>Why:</strong> maximises placental blood flow, and links the release breathing to a position you'll use in labour and in sleep.","left+side+lying+pregnancy+pillow+support"]};
MOVES.forEach(m=>{m.long=EXTRA[m.n][0];m.q=EXTRA[m.n][1];});
