
// long-form coaching cues + demo search terms, keyed to the pose table above.
// The anterior-tilt movements carry the WHY: short/overactive hip flexors (iliopsoas,
// rectus femoris) + lumbar erectors vs long/inhibited glutes + deep abdominals.
const EXTRA={
"Dead bug":["<strong>Form:</strong> Knees over hips, shins level, arms to the ceiling. Exhale, ribs down, low back pressed flat — then lower one arm overhead as the OPPOSITE leg reaches long, only as far as the back stays glued down. <strong>Why:</strong> anterior tilt means the deep abdominals are long and weak — this trains them to hold the pelvis while the limbs move. The exercise is the flat back, not the reach.","dead+bug+exercise+core+anti+extension"],
"Glute bridge":["<strong>Form:</strong> Feet flat near the fingertips, gentle tuck first, then drive through the HEELS to a straight knee–hip–shoulder line. Squeeze at the top; don't arch higher. <strong>Why:</strong> the glutes are the inhibited half of anterior tilt — if they don't produce hip extension, the lumbar erectors will. The tuck keeps them switched off and the glutes on.","glute+bridge+proper+form+posterior+tilt"],
"Half-kneeling hip flexor stretch":["<strong>Form:</strong> Front shin vertical. Squeeze the rear glute and tuck the tail FIRST — that alone is most of the stretch — then shift forward an inch or two. Feel it in the front of the rear hip, never the low back. <strong>Why:</strong> the iliopsoas and rectus femoris are the short, tight half of anterior tilt; they attach to the lumbar spine, so an arched back slackens the stretch and defeats it.","half+kneeling+hip+flexor+stretch+posterior+tilt"],
"Dumbbell bent-over row":["<strong>Form:</strong> Hinge to ~45°, back flat, and hold that angle — no heaving. Drive the elbows up and back toward the hips, squeeze the blades, lower slow. <strong>Grip note:</strong> palms facing each other or facing back only — never underhand (distal bicep rehab). Pull with the elbows, not the hands.","dumbbell+bent+over+row+two+arm+form"],
"Bench dips":["<strong>Form:</strong> Shoulders down and back before you bend. Elbows track straight back, body close to the bench, and STOP when the upper arms are parallel to the floor — treat parallel as the floor of every rep. <strong>Shoulder note:</strong> below parallel drives the humeral head forward into the separated right AC joint. If it pinches even at parallel, shorten the range further.","bench+dip+partial+range+shoulder+safe"],
"Prone Y-T-W raise":["<strong>Form:</strong> Forehead down, blades drawn down away from the ears before each lift. Y overhead (lower traps) → T out to the sides (mid traps) → W elbows bent (rear delts + external rotators), thumbs up throughout. Tiny floats — the squeeze is the work, not the height. Zero load on the AC joint.","prone+y+t+w+raise+lower+trap"],
"Wall slide":["<strong>Form:</strong> Ribs down, forearms glued to the wall, press lightly IN as you slide up — that press fires the serratus. Go only as high as the ribs stay down; an arched back is borrowed range, not shoulder motion.","wall+slide+serratus+scapular+upward+rotation"],
"Farmer hold":["<strong>Form:</strong> Stand tall and motionless: ribs stacked over pelvis, shoulders packed down and back, crush grip, breathe behind the brace. The set ends when posture — not grip — starts to lose.","farmer+carry+static+hold+posture"],
"Standing quad + hip flexor stretch":["<strong>Form:</strong> Knees together, squeeze the glute and tuck the pelvis — belt buckle to ribs — THEN let the knee drift slightly back. Never arch or lean back: that recreates the exact tilt pattern being corrected. <strong>Why:</strong> the tuck converts a plain quad stretch into a rectus femoris stretch, the two-joint muscle that tips the pelvis forward.","standing+quad+hip+flexor+stretch+pelvic+tilt"],
"Cat-cow":["<strong>Form:</strong> Inhale into cow — tail tips up, belly drops, chest lifts, one vertebra at a time. Exhale into cat — tuck, round, push the floor away to dome the stiff mid-back. Let the wave travel; don't hinge it all at the low back.","cat+cow+segmental+spinal+mobility"],
"Posture reset":["<strong>Form:</strong> One full audible exhale — feel the ribs come down and in and the pelvis settle neutral. Keep that stack and breathe quietly into the lower ribs and LOW BACK, 360°, exhale longer than the inhale. <strong>Why:</strong> this is the tilt correction in one drill — un-flared ribs over a neutral pelvis is the position everything else trained.","standing+posture+reset+rib+pelvis+stack+breathing"]};
MOVES.forEach(m=>{m.long=EXTRA[m.n][0]; m.q=EXTRA[m.n][1];});
