const EXTRA={
"Bouncing in place":["<strong>Form:</strong> Light, quick bounces on the balls of the feet. Knees soft, shoulders relaxed, arms loose. Let everything jiggle. <strong>Ankle note:</strong> if the right peroneal tendon objects, swap this for heel-to-toe rocks with the feet never leaving the floor.","qi+gong+bouncing+shaking+warmup"],
"Arm sweeps with knee dip":["<strong>Form:</strong> Both arms sweep forward and up, then back behind you as the knees dip. Continuous and pendulum-like — arms and knees move together. <strong>Targets:</strong> dynamic hip hinge, glutes and hamstrings, chest opening on the forward sweep.","qi+gong+arm+swings+front+back+knee+bend"],
"Punching rotations":["<strong>Form:</strong> Stand tall, feet a bit wider than the shoulders, knees soft. Rotate from the waist and punch slowly, pushing the shoulder blade forward at the end of each punch","qi+gong+punching+rotation+exercise"],
"Dynamic lateral reaches":["<strong>Form:</strong> Feet wide, one hand resting on the hip. Reach the other arm straight up and over the top as you bend sideways — a standing crescent, hip to fingertips. Alternate sides in one continuous arc. <strong>Targets:</strong> the lateral fascial line connecting IT band, obliques and lats. Addresses your right-side asymmetry.","dynamic+lateral+reach+side+bend+flow"],
"Cross-body knee drives":["<strong>Form:</strong> Drive one knee up and across the midline while the opposite elbow pulls down to meet it, then plant both feet before the next drive — plant, drive, plant, drive. Stay tall between reps. <strong>Targets:</strong> hip flexors plus rotational core — obliques and glute medius together, your two biggest IT band protectors.","standing+cross+body+knee+drive+exercise"],
"Chest opener swings":["<strong>Form:</strong> Arms swing wide open, then cross in front. Alternate which arm crosses on top. <strong>Targets:</strong> opening fires rhomboids and lower trap; closing fires serratus. Both sides of your mid-back equation, in a range that's safe for the right AC joint.","dynamic+chest+opener+arm+swings+exercise"],
"Hip circles":["<strong>Form:</strong> Hands on hips, feet planted. Push the hips forward, to the side, back and around. Half the time each direction. Make the circles big. <strong>Targets:</strong> hip capsule in every plane, IT band fascial connections, hip flexors.","standing+hip+circles+mobility+exercise"],
"Bent rotation sweeps":["<strong>Form:</strong> Hinge forward about 45° and rotate side to side, sweeping the arms until they stack into one vertical line — bottom hand pointing at the floor, top hand at the sky. Hips stay facing forward — rotation comes from the spine. <strong>Targets:</strong> thoracic rotation under a gravity load, more effective than the upright version.","bent+over+spinal+rotation+windmill+qi+gong"],
"Folded cat-cows":["<strong>Form:</strong> Knees bent, hands resting on them. Round the spine on the exhale, arch and open the chest on the inhale. <strong>Training link:</strong> targets T4–T8 extension — where your chronic mid-back pain lives.","standing+folded+cat+cow+spinal+mobility"],
"Cobra press-ups":["<strong>Form:</strong> Face down, hands under shoulders. Press the chest up, hips stay on the floor. Lower with control. <strong>Shoulder note:</strong> elbows tucked close to the ribs — flaring them loads the right AC joint.","cobra+press+up+mckenzie+extension"],
"Pedaling down dog":["<strong>Form:</strong> Alternate pressing one heel toward the floor while the other knee bends. Slow and rhythmic. <strong>Ankle note:</strong> gentle calf and Achilles work with no peroneal load — keep the foot tracking straight, not rolling outward.","pedaling+downward+dog+calf+stretch"],
"Thread the needle":["<strong>Form:</strong> On hands and knees. Reach one arm to the ceiling, then slide it under the opposite armpit and let the shoulder rest toward the floor. Switch at the halfway chime. <strong>Training link:</strong> thoracic rotation plus scapular mobility — your mid-back and right shoulder IR limitation.","thread+the+needle+thoracic+rotation+stretch"],
"90/90 with a fold":["<strong>Form:</strong> Z-sit: front leg's outer thigh and shin flat on the floor, back leg's inner thigh down with the shin pointing straight behind you. Sit tall, then hinge forward over the front shin without rounding","90+90+hip+stretch+with+forward+fold"]};
MOVES.forEach(m=>{m.long=EXTRA[m.n][0];m.q=EXTRA[m.n][1];});
