const EXTRA={
"Bouncing in place":["<strong>Form:</strong> Light, quick bounces on the balls of the feet. Knees soft, shoulders relaxed, arms loose. Let everything jiggle. <strong>Ankle note:</strong> if the right peroneal tendon objects, swap this for heel-to-toe rocks with the feet never leaving the floor.","qi+gong+bouncing+shaking+warmup"],
"Rotations with shoulder slaps":["<strong>Form:</strong> Rotate the upper body side to side, arms completely loose. At each end of the twist the front hand folds up and slaps the opposite shoulder while the back hand wraps behind and taps the opposite low back. Drive from the waist, not the arms. <strong>Targets:</strong> T4–T8 rotation, where your chronic mid-back pain lives.","qi+gong+twisting+body+slapping+shoulders"],
"Arm sweeps with knee dip":["<strong>Form:</strong> Both arms sweep forward and up, then back behind you as the knees dip. Continuous and pendulum-like — arms and knees move together. <strong>Targets:</strong> dynamic hip hinge, glutes and hamstrings, chest opening on the forward sweep.","qi+gong+arm+swings+front+back+knee+bend"],
"Punching rotations":["<strong>Form:</strong> Stand tall, feet a bit wider than the shoulders, knees soft. Rotate from the waist and punch slowly, pushing the shoulder blade forward at the end of each punch","qi+gong+punching+rotation+exercise"],
"Dynamic lateral reaches":["<strong>Form:</strong> Feet wide, one hand resting on the hip. Reach the other arm straight up and over the top as you bend sideways — a standing crescent, hip to fingertips. Alternate sides in one continuous arc. <strong>Targets:</strong> the lateral fascial line connecting IT band, obliques and lats. Addresses your right-side asymmetry.","dynamic+lateral+reach+side+bend+flow"],
"Cross-body knee drives":["<strong>Form:</strong> Drive one knee up and across the midline while the opposite elbow pulls down to meet it, then plant both feet before the next drive — plant, drive, plant, drive. Stay tall between reps. <strong>Targets:</strong> hip flexors plus rotational core — obliques and glute medius together, your two biggest IT band protectors.","standing+cross+body+knee+drive+exercise"],
"Chest opener swings":["<strong>Form:</strong> Arms swing wide open, then cross in front. Alternate which arm crosses on top. <strong>Targets:</strong> opening fires rhomboids and lower trap; closing fires serratus. Both sides of your mid-back equation, in a range that's safe for the right AC joint.","dynamic+chest+opener+arm+swings+exercise"],
"Hip circles":["<strong>Form:</strong> Hands on hips, feet planted. Push the hips forward, to the side, back and around. Half the time each direction. Make the circles big. <strong>Targets:</strong> hip capsule in every plane, IT band fascial connections, hip flexors.","standing+hip+circles+mobility+exercise"],
"Bent rotation sweeps":["<strong>Form:</strong> Hinge forward about 45° and rotate side to side, sweeping the arms until they stack into one vertical line — bottom hand pointing at the floor, top hand at the sky. Hips stay facing forward — rotation comes from the spine. <strong>Targets:</strong> thoracic rotation under a gravity load, more effective than the upright version.","bent+over+spinal+rotation+windmill+qi+gong"],
"Lateral weight shifts":["<strong>Form:</strong> Wide stance, shift fully into one hip and sink. Press through the <em>outside</em> edge of the planted foot. Arms sweep across in the direction of travel. <strong>Targets:</strong> pressing the outside edge is active eversion — dynamic peroneal work, plus glute medius loading. Zero impact.","standing+lateral+weight+shift+exercise+hip"]};
MOVES.forEach(m=>{m.long=EXTRA[m.n][0];m.q=EXTRA[m.n][1];});
