const EXTRA={
"Seated breathing":["<strong>Form:</strong> Sit tall on a chair or birth ball, feet flat on the floor, hands resting on the thighs. Inhale through the nose and feel the ribs widen sideways — not the chest lifting. Long exhale. <strong>Why:</strong> the growing uterus crowds the diaphragm; sideways rib expansion keeps breathing efficient later on.","prenatal+diaphragmatic+breathing+rib+expansion"],
"Seated cat-cow":["<strong>Form:</strong> Hands on knees. Round the spine and tuck the pelvis on the exhale, arch gently and open the chest on the inhale. Small and slow. <strong>Why:</strong> the belly pulls the pelvis into a forward tilt and compresses the low back — moving both directions relieves it.","seated+cat+cow+pregnancy+stretch"],
"Seated side reach":["<strong>Form:</strong> Reach one arm overhead, lean gently to the opposite side, both sit bones stay down. Breathe into the stretched side. Switch at the halfway chime. <strong>Why:</strong> creates space between ribs and hips, one of the most compressed areas later in pregnancy.","seated+side+stretch+pregnancy+ribs"],
"Seated figure-4":["<strong>Form:</strong> Ankle across the opposite knee, sit tall, hinge forward from the hips until the outer hip opens. Switch at the halfway chime. <strong>Why:</strong> relaxin loosens the pelvic ligaments and the piriformis tightens to compensate, which can irritate the sciatic nerve.","seated+figure+four+piriformis+stretch+pregnancy"],
"Supported butterfly":["<strong>Form:</strong> Sit on a cushion so the hips are above the knees. Soles together, knees falling open. Let gravity do it — never push the knees down. <strong>Why:</strong> adductor flexibility affects how wide the pelvic outlet can open. Gentle beats aggressive; the ligaments are already softened.","supported+bound+angle+butterfly+pose+pregnancy"],
"Wide-knee child's pose":["<strong>Form:</strong> Knees wide, big toes together, sit back toward the heels with the belly resting in the space between. Forearms or a cushion under the chest. <strong>Why:</strong> one of the best positions for letting the pelvic floor lengthen and release.","wide+knee+childs+pose+pregnancy+modification"],
"Hands-and-knees rocking":["<strong>Form:</strong> Wrists under shoulders. Rock the hips slowly forward and back, then in gentle circles. Spine stays neutral — no deep arching. <strong>Why:</strong> takes the baby's weight off the spine and encourages an optimal anterior fetal position.","hands+and+knees+pelvic+rocking+pregnancy"],
"Kneeling hip flexor stretch":["<strong>Form:</strong> Half-kneeling, cushion under the back knee, hand on a chair. Tuck the pelvis slightly, then shift gently forward. Switch at the halfway chime. <strong>Why:</strong> tight hip flexors tilt the pelvis forward and worsen back pain.","kneeling+hip+flexor+stretch+pregnancy+safe"],
"Standing calf stretch":["<strong>Form:</strong> Hands on a wall, one foot back with the heel pressing down, back leg straight. Switch at the halfway chime. <strong>Why:</strong> calf cramps and swelling are among the most common second and third trimester complaints.","standing+calf+stretch+wall+pregnancy"],
"Doorway chest opener":["<strong>Form:</strong> One forearm vertical on the doorframe, elbow at shoulder height, step gently through until the chest opens. Switch arms at the halfway chime. A mild stretch is plenty. <strong>Why:</strong> breast growth and the forward weight shift round the shoulders; opening the chest gives the lungs more room.","doorway+chest+stretch+pregnancy+posture"],
"Left side-lying rest":["<strong>Form:</strong> Left side, pillow between the knees and one under the belly. Slow breathing. Nothing to do here. <strong>Why:</strong> left side-lying keeps pressure off the vena cava and maximises blood flow to the placenta — a good sleeping habit to build now.","left+side+lying+position+pregnancy+pillow+support"]};
MOVES.forEach(m=>{m.long=EXTRA[m.n][0];m.q=EXTRA[m.n][1];});
